# -*- coding: utf-8 -*-
"""As 61 faixas rasterizadas do curso, lidas visualmente em 2026-08-20.
Sao imagem: nao tem camada de texto, nao saem no Ctrl+F do aluno."""
RASTERIZADAS = {
 ('Aula 00', 3):   'REGIME JURÍDICO ADMINISTRATIVO',
 ('Aula 00', 7):   'PRINCÍPIOS EXPRESSOS',
 ('Aula 01', 13):  'ADMINISTRAÇÃO PÚBLICA',
 ('Aula 02', 3):   'ORGANIZAÇÃO ADMINISTRATIVA',
 ('Aula 05', 3):   'DEVERES E PODERES ADMINISTRATIVOS',
 ('Aula 05', 5):   'PODERES ADMINISTRATIVOS',
 ('Aula 05', 29):  'USO E ABUSO DE PODER',
 ('Aula 05', 31):  'QUESTÕES PARA FIXAÇÃO',
 ('Aula 05', 93):  'QUESTÕES COMENTADAS NA AULA',
 ('Aula 05', 119): 'GABARITO',
 ('Aula 05', 120): 'REFERÊNCIAS',
 ('Aula 07', 14):  'PRINCÍPIOS',
 ('Aula 07', 27):  'OBJETIVOS DA LICITAÇÃO',
 ('Aula 07', 31):  'AGENTES PÚBLICOS DA LICITAÇÃO',
 ('Aula 07', 37):  'MODALIDADES DE LICITAÇÃO',
 ('Aula 07', 100): 'QUESTÕES',
 ('Aula 07', 127): 'LISTA DE QUESTÕES',
 ('Aula 07', 131): 'GABARITO',
 ('Aula 07', 132): 'REFERÊNCIAS',
 ('Aula 08', 51):  'FASES DA LICITAÇÃO',
 ('Aula 08', 115): 'QUESTÕES',
 ('Aula 08', 132): 'LISTA DE QUESTÕES',
 ('Aula 08', 133): 'GABARITO',
 ('Aula 08', 134): 'REFERÊNCIAS',
 ('Aula 09', 8):   'CARACTERÍSTICAS DOS CONTRATOS ADMINISTRATIVOS',
 ('Aula 09', 23):  'CLÁUSULAS EXORBITANTES',
 ('Aula 09', 33):  'DURAÇÃO DOS CONTRATOS',
 ('Aula 09', 42):  'RESPONSABILIDADES PELA EXECUÇÃO E PELOS ENCARGOS DO CONTRATO',
 ('Aula 09', 45):  'EXTINÇÃO DOS CONTRATOS',
 ('Aula 09', 54):  'NULIDADES',
 ('Aula 09', 58):  'ALTERAÇÃO DOS CONTRATOS, ALOCAÇÃO DE RISCOS E EQUILÍBRIO ECONÔMICO-FINANCEIRO',
 ('Aula 09', 66):  'INEXECUÇÃO SEM CULPA E A TEORIA DA IMPREVISÃO',
 ('Aula 09', 73):  'MEIOS ALTERNATIVOS DE RESOLUÇÃO DE CONTROVÉRSIAS',
 ('Aula 09', 76):  'IRREGULARIDADES',
 ('Aula 10', 8):   'CONCESSÃO DE SERVIÇO PÚBLICO',
 ('Aula 11', 3):   'PARCERIAS PÚBLICO-PRIVADAS',
 ('Aula 11', 25):  'QUESTÕES PARA FIXAÇÃO',
 ('Aula 11', 51):  'LISTA DE QUESTÕES',
 ('Aula 11', 62):  'GABARITO',
 ('Aula 11', 63):  'QUESTÕES PARA FIXAÇÃO',
 ('Aula 11', 74):  'LISTA DE QUESTÕES',
 ('Aula 11', 79):  'GABARITO',
 ('Aula 12', 17):  'QUESTÕES COMENTADAS',
 ('Aula 12', 21):  'QUESTÕES INÉDITAS COM COMENTÁRIOS',
 ('Aula 12', 26):  'LISTA DE QUESTÕES',
 ('Aula 12', 27):  'GABARITO',
 ('Aula 12', 28):  'LISTA DE QUESTÕES SEM COMENTÁRIOS',
 ('Aula 12', 30):  'GABARITO',
 ('Aula 14', 3):   'RESPONSABILIDADE CIVIL DO ESTADO',
 ('Aula 14', 19):  'QUESTÕES PARA FIXAÇÃO',
 ('Aula 14', 76):  'QUESTÕES COMENTADAS NA AULA',
 ('Aula 14', 102): 'GABARITO',
 ('Aula 17', 23):  'QUESTÕES PARA FIXAÇÃO',
 ('Aula 17', 67):  'QUESTÕES COMENTADAS NA AULA',
 ('Aula 17', 85):  'GABARITO',
}
# paginas com DUAS faixas (a segunda e' "REFERÊNCIAS", logo abaixo do GABARITO)
SEGUNDA_FAIXA = {
 ('Aula 11', 62): 'REFERÊNCIAS',
 ('Aula 11', 79): 'REFERÊNCIAS',
 ('Aula 14', 102): 'REFERÊNCIAS',
 ('Aula 17', 85): 'REFERÊNCIAS',
}
