# -*- coding: utf-8 -*-
"""Titulos que sao IMAGEM (sem camada de texto), lidos visualmente em 2026-08-20.
Chave: (aula, pagina) -> lista de titulos naquela pagina, na ordem em que aparecem."""
TIT_IMAGEM = {
 ('Aula 00', 3):  ['Regime de Direito Público e de Direito Privado',
                   'Regime Jurídico Aplicável à Administração Pública'],
 ('Aula 00', 5):  ['Princípios da Administração Pública – Noções Gerais'],
 ('Aula 00', 7):  ['Princípio da Legalidade'],
 ('Aula 00', 8):  ['Princípio da impessoalidade'],
 ('Aula 00', 10): ['Princípio da publicidade'],
 ('Aula 00', 11): ['Princípio da eficiência'],
 ('Aula 01', 13): ['Conceito de Estado'],
 ('Aula 01', 19): ['Sistema de governo'],
 ('Aula 01', 20): ['Administração pública em sentido amplo e em sentido estrito'],
 ('Aula 01', 21): ['Administração pública em sentido subjetivo, formal ou orgânico'],
 ('Aula 01', 23): ['Administração pública em sentido objetivo, material ou funcional'],
 ('Aula 02', 3):  ['Entidades políticas e administrativas'],
 ('Aula 02', 5):  ['Centralização e descentralização'],
 ('Aula 02', 9):  ['Concentração e Desconcentração'],
 ('Aula 02', 11): ['Capacidade processual', 'Criação dos órgãos públicos'],
 ('Aula 05', 7):  ['Poder hierárquico'],
 ('Aula 06', 13): ['Presunção de legitimidade ou veracidade'],
 ('Aula 06', 16): ['Autoexecutoriedade'],
 ('Aula 07', 16): ['Vedação à restrição do caráter competitivo da licitação'],
 ('Aula 07', 18): ['Publicidade, transparência e sigilo das propostas'],
 ('Aula 07', 21): ['Segregação de funções'],
 ('Aula 07', 22): ['Vinculação ao edital'],
 ('Aula 07', 23): ['Julgamento objetivo', 'Desenvolvimento nacional sustentável'],
 ('Aula 07', 24): ['Adjudicação compulsória (princípio implícito)'],
 ('Aula 07', 50): ['Diálogo competitivo'],
 ('Aula 07', 51): ['Quando é possível adotar o diálogo competitivo?',
                   'Etapas do diálogo competitivo'],
 ('Aula 07', 53): ['Comissão de contratação'],
 ('Aula 08', 51): ['Disposições gerais'],
 ('Aula 08', 52): ['Divulgação do edital de licitação', 'Publicidade do edital'],
 ('Aula 08', 53): ['Prazo para apresentação de propostas e lances'],
 ('Aula 08', 60): ['Desclassificação de propostas'],
 ('Aula 08', 62): ['Negociação de condições mais vantajosas'],
 ('Aula 09', 8):  ['Natureza de contrato de adesão'],
 ('Aula 09', 9):  ['Natureza intuitu personae'],
 ('Aula 09', 10): ['Solenidades dos contratos'],
 ('Aula 09', 12): ['Instrumento de contrato'],
 ('Aula 09', 16): ['Formalização dos contratos e cláusulas necessárias'],
 ('Aula 09', 17): ['Convocação do contratado'],
 ('Aula 09', 19): ['Convocação para cumprir o remanescente'],
 ('Aula 09', 26): ['Ocupação provisória',
                   'Restrição à oposição da exceção do contrato não cumprido'],
 ('Aula 09', 33): ['Prazos de vigência', 'Contratos de serviços e fornecimentos contínuos'],
 ('Aula 09', 35): ['Administração como usuária de serviços públicos'],
 ('Aula 09', 36): ['Contrato que gere receita e contrato de eficiência'],
 ('Aula 09', 37): ['Contrato por escopo'],
 ('Aula 09', 38): ['Regime de fornecimento e prestação de serviço associado'],
 ('Aula 09', 39): ['Contratos de operação continuada de sistemas estruturantes de tecnologia da informação'],
 ('Aula 09', 40): ['Resumo dos prazos de vigência dos contratos'],
 ('Aula 09', 42): ['Responsabilidade pela execução', 'Responsabilidade pelos encargos'],
 ('Aula 09', 45): ['Hipóteses de extinção'],
 ('Aula 09', 47): ['Direito subjetivo do contratado à extinção'],
 ('Aula 09', 49): ['Espécies ou formas de extinção do contrato'],
 ('Aula 09', 51): ['Consequências da extinção do contrato'],
 ('Aula 09', 58): ['Formas de alteração dos contratos', 'Alteração unilateral'],
 ('Aula 09', 60): ['Alteração por acordo das partes (consensual)'],
 ('Aula 09', 62): ['Equilíbrio econômico-financeiro (reajuste e revisão)'],
 ('Aula 09', 67): ['Caso fortuito e força maior'],
 ('Aula 09', 71): ['Interferências imprevistas'],
 ('Aula 09', 77): ['Sanções administrativas'],
 ('Aula 09', 78): ['Aplicação das sanções'],
 ('Aula 09', 84): ['Reabilitação do licitante ou contratado'],
 ('Aula 10', 8):  ['Modalidades de delegação de serviços públicos'],
 ('Aula 10', 11): ['Definição e modalidades de concessão'],
 ('Aula 10', 15): ['Contrato de concessão'],
 ('Aula 10', 16): ['Serviço público adequado'],
 ('Aula 10', 17): ['Prerrogativas do poder concedente'],
 ('Aula 10', 18): ['Extinção da concessão'],
 ('Aula 11', 3):  ['Modalidades de parcerias'],
 ('Aula 11', 4):  ['Vedações e diretrizes das PPP'],
 ('Aula 11', 5):  ['Contrato de parceria público-privada'],
 ('Aula 11', 7):  ['Sociedade de propósito específicos'],
 ('Aula 11', 8):  ['Licitação prévia à contratação de parcerias público-privadas'],
 ('Aula 11', 10): ['Jurisprudência de PPP',
                   'Queda na arrecadação municipal e diminuição da contraprestação nos contratos de PPPs'],
 ('Aula 14', 3):  ['Evolução histórica', 'Teoria da irresponsabilidade do Estado'],
 ('Aula 14', 4):  ['Teoria da culpa administrativa', 'Teoria do risco administrativo'],
 ('Aula 14', 5):  ['Responsabilidade civil do Estado no direito brasileiro'],
 ('Aula 14', 7):  ['Requisitos para a demonstração da responsabilidade do Estado'],
 ('Aula 14', 9):  ['Causas excludentes ou atenuantes da responsabilidade do Estado',
                   'Caso fortuito ou força maior'],
 ('Aula 14', 10): ['Culpa exclusiva da vítima', 'Ato exclusivo de terceiro',
                   'Responsabilidade por omissão do Estado'],
 ('Aula 14', 12): ['O Estado como “garante”'],
 ('Aula 14', 13): ['Reparação do dano – Estado indenizando o terceiro lesado',
                   'Direito de regresso'],
 ('Aula 14', 16): ['Responsabilidade civil por atos não administrativos',
                   'Responsabilidade civil por ato legislativo'],
 ('Aula 14', 17): ['Responsabilidade civil por ato jurisdicional'],
}
# descartado: ('Aula 15', 124) e' o mascote decorativo "ESCLARECENDO!", nao e' titulo
